### ISSUE TITLE
Restore git submodules to enable building of Sonarflow app

### ISSUE THREAD

**Issue by epei** [spectralmind/sonarflow-ios#1]
Sonarflow references a number of git submodules. 

There are three cases:
1. Pertinent source code for Sonarflow itself (bubbleview, ...)
2. 3rd party libraries without any modifications
3. 3rd party libraries which have been modified/enhanced.

**Case 1**: The source code is included in this repository.
**Case 2 and 3**: These need to be identified and either referenced from the original author's repository, or, also included in this repository. This will be decided individually.

**Comment by fabb** [comment]
done!
